const cartTypes ={
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_CART_ITEM:"REMOVE_CART_ITEM",
    REDUCE_CART_ITEM:"REDUCE_CART_ITEM",
   SAVE_CART_SHIPPING_ADDRESS:"SAVE_CART_SHIPPING_ADDRESS",
   SAVE_CART_PAYMENT_METHOD:"SAVE_CART_PAYMENT_METHOD"
    
}

export default cartTypes;