 const productTypes = {
     FETCH_PRODUCTS_REQUEST:"FETCH_PRODUCTS_REQUEST",
     SET_PRODUCTS:"SET_PRODUCTS",
     FETCH_PRODUCTS_FAIL:"FETCH_PRODUCTS_FAIL",
     
     FETCH_PRODUCT_REQUEST:"FETCH_PRODUCT_REQUEST",
     SET_PRODUCT:"SET_PRODUCT",
     FETCH_PRODUCT_FAIL:"FETCH_PRODUCT_FAIL",
}
 
 export default productTypes