export const userTypes={
    USER_SIGNIN_REQUEST:"USER_SIGNIN_REQUEST",
    USER_SIGNIN_SUCCESS:"USER_SIGNIN_SUCCESS",
    USER_SIGNIN_FAIL:"USER_SIGNIN_FAIL",
    USER_SIGNIN_ERROR:"USER_SIGNIN_ERROR",
    USER_SIGNOUT_SUCCESS:"USER_SIGNOUT_SUCCESS",
    
    USER_SIGNUP_REQUEST:"USER_SIGNUP_REQUEST",
    USER_SIGNUP_VERIFICATION:"USER_SIGNUP_VERIFICATION",
    USER_SIGNUP_ERROR:"USER_SIGNUP_ERROR",
    USER_SIGNUP_FAIL:"USER_SIGNUP_FAIL",
}